#!/bin/sh
if [ "x$D" != "x" ] && [ -f $D/var/lib/opkg/status ]; then
	install -d $D/opt/clanton-tiny/1.4.2/sysroots/x86_64-pokysdk-linux/etc/rcS.d

	# this happens at S98 where our good 'ole packages script used to run
	echo "#!/bin/sh
opkg-cl configure >/var/log/postinstall.log 2>&1
rm -f //opt/clanton-tiny/1.4.2/sysroots/x86_64-pokysdk-linux/etc/rcS.d/S98run-postinsts
" > $D/opt/clanton-tiny/1.4.2/sysroots/x86_64-pokysdk-linux/etc/rcS.d/S98run-postinsts
	chmod 0755 $D/opt/clanton-tiny/1.4.2/sysroots/x86_64-pokysdk-linux/etc/rcS.d/S98run-postinsts
fi
	update-alternatives --install /opt/clanton-tiny/1.4.2/sysroots/x86_64-pokysdk-linux/usr/bin/opkg opkg /opt/clanton-tiny/1.4.2/sysroots/x86_64-pokysdk-linux/usr/bin/opkg-cl 100
